//! Generates PipeWire and WirePlumber config files from the current AppState.
//!
//! Node naming convention:
//!   Preset sink:       pw-ctrl.preset.{id}             (Audio/Sink, apps connect here)
//!   Preset EQ stream:  pw-ctrl.preset.{id}.eq-out      (filter-chain playback stream → eq-mix)
//!   Preset eq-mix:     pw-ctrl.preset.{id}.eq-mix      (Audio/Sink, intermediate loopback capture)
//!   Preset eq-src:     pw-ctrl.preset.{id}.eq-src      (Audio/Source, intermediate loopback playback)
//!   Preset loopback:   pw-ctrl.preset.{id}.loopback.[vmic|sink].{target-safe}.cap / (no .cap for playback)
//!   VirtualMic source: pw-ctrl.vmic.{id}
//!   VirtualMic mixer:  pw-ctrl.vmic.{id}.mix
//!   VirtualMic input:  pw-ctrl.vmic.{id}.in.{idx}.{source-safe}.cap / (no .cap for playback)

use std::{collections::HashMap, fmt::Write as FmtWrite, fs, path::Path};
use anyhow::Result;

use crate::{
    ladspa::{self, LadspaCatalog},
    lv2::{primary_audio_port, Lv2Catalog, PortDirection},
    preset::{ChainNode, ChainNodeKind, Preset},
    virtual_mic::VirtualMic,
};

pub const PREVIEW_DIR: &str = "/tmp/pwctl";
pub const PREVIEW_PW:  &str = "/tmp/pwctl/pipewire.conf";
pub const PREVIEW_WP:  &str = "/tmp/pwctl/pwctl-routing.conf";

pub const DEST_PW: &str = ".config/pipewire/pipewire.conf.d/pwctl.conf";
pub const DEST_WP: &str = ".config/wireplumber/wireplumber.conf.d/pwctl-routing.conf";

// ── Public API ────────────────────────────────────────────────────────────────

pub fn write_preview(
    presets: &[Preset],
    virtual_mics: &[VirtualMic],
    routes: &HashMap<String, String>,
    lv2: &Lv2Catalog,
    ladspa: &LadspaCatalog,
) -> Result<(String, String)> {
    fs::create_dir_all(PREVIEW_DIR)?;
    let pw = gen_pipewire_conf(presets, virtual_mics, lv2, ladspa);
    let wp = gen_wireplumber_conf(presets, routes);
    fs::write(PREVIEW_PW, &pw)?;
    fs::write(PREVIEW_WP, &wp)?;
    Ok((pw, wp))
}

/// Write WirePlumber routing rules directly to the live config path.
/// Called after every route/unroute so rules survive restarts without a full apply.
pub fn write_wp_routing(presets: &[Preset], routes: &HashMap<String, String>) -> Result<()> {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".into());
    let dest = Path::new(&home).join(DEST_WP);
    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(dest, gen_wireplumber_conf(presets, routes))?;
    Ok(())
}

pub fn apply_preview() -> Result<()> {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".into());
    let dest_pw = Path::new(&home).join(DEST_PW);
    let dest_wp = Path::new(&home).join(DEST_WP);
    fs::create_dir_all(dest_pw.parent().unwrap())?;
    fs::create_dir_all(dest_wp.parent().unwrap())?;
    fs::copy(PREVIEW_PW, &dest_pw)?;
    fs::copy(PREVIEW_WP, &dest_wp)?;
    Ok(())
}

// ── PipeWire config ───────────────────────────────────────────────────────────

fn gen_pipewire_conf(presets: &[Preset], virtual_mics: &[VirtualMic], lv2: &Lv2Catalog, ladspa: &LadspaCatalog) -> String {
    let mut out = String::new();
    writeln!(out, "# Generated by pipewire-control — do not edit manually").unwrap();
    writeln!(out, "context.modules = [").unwrap();
    writeln!(out).unwrap();

    for preset in presets {
        write_preset(&mut out, preset, lv2, ladspa);
    }
    for mic in virtual_mics {
        write_virtual_mic(&mut out, mic);
    }

    writeln!(out, "]").unwrap();
    out
}

// ── Preset ────────────────────────────────────────────────────────────────────
//
// Signal flow:
//   apps → pw-ctrl.preset.{id}  (Audio/Sink, filter-chain capture)
//        → EQ filter graph
//        → pw-ctrl.preset.{id}.eq-out  (filter-chain playback stream → eq-mix)
//        → pw-ctrl.preset.{id}.eq-mix  (Audio/Sink, loopback capture)
//        → pw-ctrl.preset.{id}.eq-src  (Audio/Source, loopback playback)
//        → N output loopbacks → physical sinks / vmic mixers
//
// The intermediate loopback (eq-mix → eq-src) is required because PipeWire
// capture streams (Stream/Input/Audio) can only target Audio/Source nodes.
// The filter-chain's own output is a stream that writes into eq-mix, and
// eq-src exposes that audio as a source for the output loopbacks to read.

fn write_preset(out: &mut String, preset: &Preset, lv2: &Lv2Catalog, ladspa: &LadspaCatalog) {
    let sink    = format!("pw-ctrl.preset.{}", preset.id);
    let eq_mix  = format!("pw-ctrl.preset.{}.eq-mix", preset.id);
    let eq_src  = format!("pw-ctrl.preset.{}.eq-src", preset.id);
    let eq_out  = format!("pw-ctrl.preset.{}.eq-out", preset.id); // playback stream name
    let ch      = preset.channels.channels();
    let pos     = preset.channels.position();

    writeln!(out, "  # ── Preset: {} ─────────────────────────────────────────────", preset.name).unwrap();

    // 1. Intermediate loopback: eq-mix (sink) → eq-src (source)
    //    Allows N output loopbacks to read from a single Audio/Source.
    writeln!(out, "  {{").unwrap();
    writeln!(out, "    name = libpipewire-module-loopback").unwrap();
    writeln!(out, "    args = {{").unwrap();
    writeln!(out, "      capture.props = {{").unwrap();
    writeln!(out, "        node.name        = {:?}", eq_mix).unwrap();
    writeln!(out, "        node.description = {:?}", format!("{} [internal eq-mix]", preset.name)).unwrap();
    writeln!(out, "        media.class      = \"Stream/Input/Audio\"").unwrap();
    writeln!(out, "        node.passive     = true").unwrap();
    writeln!(out, "        node.autoconnect = false").unwrap();
    writeln!(out, "        node.hidden      = true").unwrap();
    writeln!(out, "        node.virtual     = true").unwrap();
    writeln!(out, "        audio.channels   = 2").unwrap();
    writeln!(out, "        audio.position   = [ FL FR ]").unwrap();
    writeln!(out, "      }}").unwrap();
    writeln!(out, "      playback.props = {{").unwrap();
    writeln!(out, "        node.name        = {:?}", eq_src).unwrap();
    writeln!(out, "        node.description = {:?}", format!("{} [internal eq-src]", preset.name)).unwrap();
    writeln!(out, "        media.class      = \"Stream/Output/Audio\"").unwrap();
    writeln!(out, "        node.autoconnect = false").unwrap();
    writeln!(out, "        node.hidden      = true").unwrap();
    writeln!(out, "        node.virtual     = true").unwrap();
    writeln!(out, "        audio.channels   = 2").unwrap();
    writeln!(out, "        audio.position   = [ FL FR ]").unwrap();
    writeln!(out, "      }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "  }}").unwrap();
    writeln!(out).unwrap();

    // 2. Effects filter-chain: visible sink → plugin chain → stream into eq-mix
    writeln!(out, "  {{").unwrap();
    writeln!(out, "    name = libpipewire-module-filter-chain").unwrap();
    writeln!(out, "    args = {{").unwrap();
    writeln!(out, "      node.description = {:?}", preset.name).unwrap();
    writeln!(out, "      filter.graph = {{").unwrap();

    write_chain_graph(out, &preset.chain, lv2, ladspa);
    writeln!(out).unwrap();

    // capture side: the visible Audio/Sink apps connect to
    writeln!(out, "      capture.props = {{").unwrap();
    writeln!(out, "        node.name        = {:?}", sink).unwrap();
    writeln!(out, "        media.class      = \"Audio/Sink\"").unwrap();
    writeln!(out, "        node.passive     = true").unwrap();
    writeln!(out, "        node.autoconnect = false").unwrap();
    writeln!(out, "        audio.channels   = 2").unwrap();
    writeln!(out, "        audio.position   = [ FL FR ]").unwrap();
    writeln!(out, "      }}").unwrap();

    // playback side: stream that feeds into eq-mix
    writeln!(out, "      playback.props = {{").unwrap();
    writeln!(out, "        node.name        = {:?}", eq_out).unwrap();
    writeln!(out, "        target.object    = {:?}", eq_mix).unwrap();
    writeln!(out, "        node.autoconnect = true").unwrap();
    writeln!(out, "        audio.channels   = 2").unwrap();
    writeln!(out, "        audio.position   = [ FL FR ]").unwrap();
    writeln!(out, "      }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "  }}").unwrap();
    writeln!(out).unwrap();

    // 3. Source input loopbacks — capture from native Audio/Source, play into preset sink (goes through EQ)
    for node_name in &preset.source_inputs {
        let safe = safe_name(node_name);
        let cap_name      = format!("{sink}.src-in.{safe}.cap");
        let playback_name = format!("{sink}.src-in.{safe}");

        writeln!(out, "  # Source input: {:?} → {:?}", node_name, preset.name).unwrap();
        writeln!(out, "  {{").unwrap();
        writeln!(out, "    name = libpipewire-module-loopback").unwrap();
        writeln!(out, "    args = {{").unwrap();
        writeln!(out, "      capture.props = {{").unwrap();
        writeln!(out, "        node.name        = {:?}", cap_name).unwrap();
        writeln!(out, "        node.description = {:?}", format!("{} [src-in {} cap]", preset.name, node_name)).unwrap();
        writeln!(out, "        target.object    = {:?}", node_name).unwrap();
        writeln!(out, "      }}").unwrap();
        writeln!(out, "      playback.props = {{").unwrap();
        writeln!(out, "        node.name        = {:?}", playback_name).unwrap();
        writeln!(out, "        node.description = {:?}", format!("{} [src-in {}]", preset.name, node_name)).unwrap();
        writeln!(out, "        target.object    = {:?}", sink).unwrap();
        writeln!(out, "        node.autoconnect = true").unwrap();
        writeln!(out, "      }}").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "  }}").unwrap();
        writeln!(out).unwrap();
    }

    // 4. Output loopbacks — one per output, capture from eq-src
    for output in &preset.outputs {
        let (type_tag, safe_target) = output_type_and_safe_name(&output.node_name);
        let cap_name      = format!("{sink}.loopback.{type_tag}.{safe_target}.cap");
        let playback_name = format!("{sink}.loopback.{type_tag}.{safe_target}");

        writeln!(out, "  # Output: {:?} → {:?}", preset.name, output.node_name).unwrap();
        writeln!(out, "  {{").unwrap();
        writeln!(out, "    name = libpipewire-module-loopback").unwrap();
        writeln!(out, "    args = {{").unwrap();
        writeln!(out, "      capture.props = {{").unwrap();
        writeln!(out, "        node.name        = {:?}", cap_name).unwrap();
        writeln!(out, "        node.description = {:?}", format!("{} → {} [internal]", preset.name, output.node_name)).unwrap();
        writeln!(out, "        target.object    = {:?}", eq_src).unwrap();
        writeln!(out, "        node.passive     = true").unwrap();
        writeln!(out, "        node.hidden      = true").unwrap();
        writeln!(out, "        audio.channels   = {ch}").unwrap();
        writeln!(out, "        audio.position   = {pos}").unwrap();
        writeln!(out, "      }}").unwrap();
        writeln!(out, "      playback.props = {{").unwrap();
        writeln!(out, "        node.name        = {:?}", playback_name).unwrap();
        writeln!(out, "        node.description = {:?}", format!("{} → {}", preset.name, output.node_name)).unwrap();
        writeln!(out, "        target.object    = {:?}", output.node_name).unwrap();
        writeln!(out, "        node.autoconnect = true").unwrap();
        writeln!(out, "        audio.channels   = {ch}").unwrap();
        writeln!(out, "        audio.position   = {pos}").unwrap();
        writeln!(out, "      }}").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "  }}").unwrap();
        writeln!(out).unwrap();
    }
}

// ── Virtual Mic ───────────────────────────────────────────────────────────────
//
// Structure:
//   1. loopback: mixer sink (internal) → Audio/Source (visible to apps)
//   2. One filter-chain per input: source/monitor → gain → mixer sink

fn write_virtual_mic(out: &mut String, mic: &VirtualMic) {
    let source = format!("pw-ctrl.vmic.{}", mic.id);
    let mixer  = format!("pw-ctrl.vmic.{}.mix", mic.id);

    writeln!(out, "  # ── Virtual Mic: {} ─────────────────────────────────────────", mic.name).unwrap();

    // 1. The Audio/Source that apps see
    writeln!(out, "  {{").unwrap();
    writeln!(out, "    name = libpipewire-module-loopback").unwrap();
    writeln!(out, "    args = {{").unwrap();
    writeln!(out, "      node.description = {:?}", mic.name).unwrap();
    writeln!(out, "      capture.props = {{").unwrap();
    writeln!(out, "        node.name        = {:?}", mixer).unwrap();
    writeln!(out, "        node.description = {:?}", format!("{} [internal mixer]", mic.name)).unwrap();
    writeln!(out, "        media.class      = \"Stream/Input/Audio\"").unwrap();
    writeln!(out, "        node.passive     = true").unwrap();
    writeln!(out, "        node.autoconnect = false").unwrap();
    writeln!(out, "        node.hidden      = true").unwrap();
    writeln!(out, "        node.virtual     = true").unwrap();
    writeln!(out, "      }}").unwrap();
    writeln!(out, "      playback.props = {{").unwrap();
    writeln!(out, "        node.name        = {:?}", source).unwrap();
    writeln!(out, "        media.class      = \"Audio/Source\"").unwrap();
    writeln!(out, "        node.autoconnect = false").unwrap();
    writeln!(out, "      }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "  }}").unwrap();
    writeln!(out).unwrap();

    // 2. One filter-chain per input (applies gain, sends to mixer)
    for (idx, input) in mic.inputs.iter().enumerate() {
        let safe = safe_name(&input.node_name);
        let cap_name      = format!("{source}.in.{idx}.{safe}.cap");
        let playback_name = format!("{source}.in.{idx}.{safe}");

        writeln!(out, "  # Input {idx}: {:?}", input.node_name).unwrap();
        writeln!(out, "  {{").unwrap();
        writeln!(out, "    name = libpipewire-module-filter-chain").unwrap();
        writeln!(out, "    args = {{").unwrap();
        writeln!(out, "      node.description = {:?}", format!("{} in{idx}", mic.name)).unwrap();
        writeln!(out, "      filter.graph = {{").unwrap();
        writeln!(out, "        nodes = [").unwrap();
        writeln!(out, "          {{ type = builtin  name = gain  label = multiply  control = {{ \"Multiplier\" = {} }} }}", input.gain).unwrap();
        writeln!(out, "        ]").unwrap();
        writeln!(out, "        links = []").unwrap();
        writeln!(out, "        inputs  = [ \"gain:In\" ]").unwrap();
        writeln!(out, "        outputs = [ \"gain:Out\" ]").unwrap();
        writeln!(out, "      }}").unwrap();
        writeln!(out, "      capture.props = {{").unwrap();
        writeln!(out, "        node.name     = {:?}", cap_name).unwrap();
        writeln!(out, "        target.object = {:?}", input.node_name).unwrap();
        writeln!(out, "      }}").unwrap();
        writeln!(out, "      playback.props = {{").unwrap();
        writeln!(out, "        node.name        = {:?}", playback_name).unwrap();
        writeln!(out, "        target.object    = {:?}", mixer).unwrap();
        writeln!(out, "        node.autoconnect = true").unwrap();
        writeln!(out, "      }}").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "  }}").unwrap();
        writeln!(out).unwrap();
    }
}

// ── WirePlumber routing ───────────────────────────────────────────────────────
//
// Uses the `stream.rules` section read by WirePlumber's state-stream.lua script.
// Rules in this section match stream nodes (media.class = "Stream/*") when they
// are added to the graph and apply properties to them — including `target.object`,
// which WirePlumber's linking policy reads to route the stream to a specific sink.
// This approach persists across restarts because the conf file is always loaded.

fn gen_wireplumber_conf(presets: &[Preset], routes: &HashMap<String, String>) -> String {
    let mut out = String::new();
    writeln!(out, "# Generated by pipewire-control — do not edit manually").unwrap();
    writeln!(out, "stream.rules = [").unwrap();

    for (node_name, preset_id) in routes {
        let target = format!("pw-ctrl.preset.{preset_id}");
        let preset_label = presets.iter().find(|p| &p.id == preset_id)
            .map(|p| p.name.as_str()).unwrap_or(preset_id.as_str());
        writeln!(out, "  # route: {node_name} → {preset_label}").unwrap();
        writeln!(out, "  {{").unwrap();
        writeln!(out, "    matches = [ {{ node.name = {node_name:?} }} ]").unwrap();
        writeln!(out, "    actions = {{ update-props = {{ target.object = {target:?} }} }}").unwrap();
        writeln!(out, "  }}").unwrap();
    }

    writeln!(out, "]").unwrap();
    out
}

// ── Chain → filter.graph emitter ──────────────────────────────────────────────
//
// Translates the ordered Vec<ChainNode> into the `nodes`, `links`, `inputs`,
// `outputs` blocks of a filter-chain graph. Bypassed nodes and unknown LV2
// plugins (not present in the cached catalog) become `builtin copy` so the
// graph topology stays consistent.

fn write_chain_graph(out: &mut String, chain: &[ChainNode], lv2: &Lv2Catalog, ladspa_cat: &LadspaCatalog) {
    // Resolve each chain node into (graph_name, in_symbol, out_symbol, body).
    struct Resolved {
        name: String,
        in_sym: String,
        out_sym: String,
    }
    let mut resolved: Vec<Resolved> = Vec::with_capacity(chain.len());

    writeln!(out, "        nodes = [").unwrap();
    for node in chain {
        let name = sanitize_graph_id(&node.id);
        let (in_sym, out_sym) = if node.bypass {
            writeln!(out, "          {{ type = builtin  name = {name}  label = copy }}").unwrap();
            ("In".into(), "Out".into())
        } else {
            match &node.kind {
                ChainNodeKind::Lv2 { plugin_uri, controls } => {
                    let plugin = lv2.find(plugin_uri);
                    let (in_sym, out_sym) = plugin
                        .and_then(|p| {
                            let i = primary_audio_port(p, PortDirection::Input)?.symbol.clone();
                            let o = primary_audio_port(p, PortDirection::Output)?.symbol.clone();
                            Some((i, o))
                        })
                        .unwrap_or_else(|| ("in".into(), "out".into()));
                    write!(out, "          {{ type = lv2  name = {name}  plugin = {:?}", plugin_uri).unwrap();
                    if !controls.is_empty() {
                        write!(out, "  control = {{").unwrap();
                        for (sym, val) in controls {
                            write!(out, " {:?} = {}", sym, val).unwrap();
                        }
                        write!(out, " }}").unwrap();
                    }
                    writeln!(out, " }}").unwrap();
                    (in_sym, out_sym)
                }
                ChainNodeKind::Builtin { label, controls } => {
                    write!(out, "          {{ type = builtin  name = {name}  label = {label}").unwrap();
                    if !controls.is_empty() {
                        write!(out, "  control = {{").unwrap();
                        for (sym, val) in controls {
                            write!(out, " {:?} = {}", sym, val).unwrap();
                        }
                        write!(out, " }}").unwrap();
                    }
                    writeln!(out, " }}").unwrap();
                    ("In".into(), "Out".into())
                }
                ChainNodeKind::Ladspa { path, label, controls } => {
                    let plugin = ladspa_cat.find_pair(path, label);
                    let (in_sym, out_sym) = plugin
                        .and_then(|p| {
                            let i = ladspa::primary_audio_port(p, ladspa::PortDirection::Input)?.name.clone();
                            let o = ladspa::primary_audio_port(p, ladspa::PortDirection::Output)?.name.clone();
                            Some((i, o))
                        })
                        .unwrap_or_else(|| ("Input".into(), "Output".into()));
                    write!(out, "          {{ type = ladspa  name = {name}  plugin = {:?}  label = {:?}", path, label).unwrap();
                    if !controls.is_empty() {
                        write!(out, "  control = {{").unwrap();
                        for (sym, val) in controls {
                            write!(out, " {:?} = {}", sym, val).unwrap();
                        }
                        write!(out, " }}").unwrap();
                    }
                    writeln!(out, " }}").unwrap();
                    (in_sym, out_sym)
                }
            }
        };
        resolved.push(Resolved { name, in_sym, out_sym });
    }

    if resolved.is_empty() {
        // Empty chain → single passthrough so the filter-chain stays valid.
        writeln!(out, "          {{ type = builtin  name = passthrough  label = copy }}").unwrap();
    }
    writeln!(out, "        ]").unwrap();

    writeln!(out, "        links = [").unwrap();
    for pair in resolved.windows(2) {
        let a = &pair[0]; let b = &pair[1];
        writeln!(out, "          {{ output = \"{}:{}\"  input = \"{}:{}\" }}",
                 a.name, a.out_sym, b.name, b.in_sym).unwrap();
    }
    writeln!(out, "        ]").unwrap();

    let (gi, go) = if let (Some(first), Some(last)) = (resolved.first(), resolved.last()) {
        (format!("{}:{}", first.name, first.in_sym), format!("{}:{}", last.name, last.out_sym))
    } else {
        ("passthrough:In".into(), "passthrough:Out".into())
    };
    writeln!(out, "        inputs  = [ \"{gi}\" ]").unwrap();
    writeln!(out, "        outputs = [ \"{go}\" ]").unwrap();
    writeln!(out, "      }}").unwrap();
}

fn sanitize_graph_id(id: &str) -> String {
    let s: String = id.chars().map(|c| if c.is_ascii_alphanumeric() { c } else { '_' }).collect();
    if s.is_empty() || s.chars().next().unwrap().is_ascii_digit() {
        format!("n_{s}")
    } else {
        s
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn safe_name(node_name: &str) -> String {
    node_name
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' { c } else { '_' })
        .collect::<String>()
        .trim_matches('_')
        .to_string()
}

/// Returns ("vmic", safe_id) for virtual mic mix targets, ("sink", safe_name) for physical sinks.
fn output_type_and_safe_name(node_name: &str) -> (&'static str, String) {
    if let Some(rest) = node_name.strip_prefix("pw-ctrl.vmic.").and_then(|s| s.strip_suffix(".mix")) {
        ("vmic", safe_name(rest))
    } else {
        ("sink", safe_name(node_name))
    }
}
